"plugins
call plug#begin()

Plug 'junegunn/vim-plug'
Plug 'ojroques/vim-oscyank', {'branch': 'main'}

call plug#end()

"vim option
set mouse=a
set number
set wrap
set tabstop=2
set softtabstop=0
set shiftwidth=2

"keybind
let mapleader = " "
let maplocalleader = "\\"
nmap <leader>c <Plug>OSCYankOperator
nmap <leader>cc <leader>c_
vmap <leader>c <Plug>OSCYankVisual

